main: eu.spectrum.main.Main
name: SpectroLikesJumping
version: v1.0
author: Spectrum
description: Spectro likes jumping, girl.
load: STARTUP

commands:
   module:
      description: Enables to manage modules.
   setup:
      description: Enables to set up the game.
   start:
      description: Starts the game.